const maqui = document.querySelector('img').addEventListener('click', total);
total();
function total() {
  const f1 = [
    ' Dado',
    ' Baixo',
    ' Como',
    ' Bola',
    ' Hoje',
    ' Amanha',
    ' Procurar',
    ' Cativeiro',
    ' Você',
    ' Bombeiros',
    ' Crescente',
    ' Tesouro',
    ' Porque',
    ' Social  ',
    ' Matemática',
    ' Milho',
    ' Ontem',
    ' Trinta',
    ' Musica',
    ' Atoa',
    ' Pato',
    ' Vida',
    ' Morte',
    ' Pato',
    ' Gato',
    ' Bosolanro',
    ' Fruta',
    ' Pena',
    ' Mesmo',
    ' Talvez',
  ];
  const f2 = [
    ' é',
    ' ,',
    ' eita',
    ' seria',
    ' quem',
    ' da',
    ' do',
    ' sim',
    ' vez',
    ' não',
    ' e',
    ' a',
    ' poxa',
    ' qual',
    ' que',
    ' isso',
    ' Pato',
    ' eu',
    ' tenha',
    ' faz',
    ' fez',
    ' para',
    ' por',
    ' vish',
    ' eita',
    ' tipo',
    ' dose',
    ' uma',
    ' mesmo',
    ' talvez',
  ];
  const f3 = [
    ' fugir',
    ' pneus',
    ' orquestra',
    ' cultura',
    ' bazuca',
    ' humano',
    ' quem',
    ' pacotes',
    ' carta',
    ' triplo',
    ' link',
    ' desligar',
    ' apertado',
    ' escolta',
    ' traseiro',
    ' tornado',
    ' laranja',
    ' cinquenta',
    ' Lula',
    ' cenoura',
    ' dividir',
    ' anedota',
    ' carro',
    ' ecologista',
    ' Pato',
    ' aventura',
    ' debate',
    ' agudo',
    ' equipamento',
    ' utilidade',
  ];
  const f4 = [
    ' é',
    ' ,',
    ' eita',
    ' seria',
    ' quem',
    ' da',
    ' do',
    ' sim',
    ' vez',
    ' não',
    ' e',
    ' a',
    ' poxa',
    ' qual',
    ' que',
    ' está',
    ' talvez',
    ' eu',
    ' tenha',
    ' faz',
    ' fez',
    ' para',
    ' por',
    ' vish',
    ' eita',
    ' outro',
    ' dose',
    ' uma',
    ' mesmo',
    ' Pato',
  ];
  const f5 = [
    ' girassol',
    ' consoantes',
    ' leite',
    ' montanha',
    ' triste',
    ' feliz',
    ' dez',
    ' derrama',
    ' praga',
    ' senta',
    ' girafa',
    ' ,',
    ' carteira',
    ' resumo',
    ' Pato',
    ' peso',
    ' manunteção',
    ' grupo',
    ' patamar',
    ' cerveja',
    ' mar',
    ' skate',
    ' borboleta',
    ' barraco',
    ' tijolo',
    ' coração',
    ' eclipse',
    ' sorrir',
    ' vera',
    ' virada',
  ];
  const f6 = [
    ' ?',
    ' !',
    ' torneio.',
    ' tomou.',
    ' Pato.',
    ' ocupado.',
    ' visita.',
    ' olho.',
    ' lagoa.',
    ' bengala.',
    ' baixo.',
    ' cubo.',
    ' corre.',
    ' cubo.',
    '?',
    '.',
    '!!',
    '...',
    ' quebra.',
    ' ei!',
    ' banco.',
    ' malote.',
    ' briga.',
    ' Matuê.',
    ' irmão.',
    ' rum.',
    ' lancha.',
    ' bem.',
    ' mal.',
    ' filme.',
  ];
  const frase1 = f1[Math.floor(Math.random() * 29)];
  const frase2 = f2[Math.floor(Math.random() * 29)];
  const frase3 = f3[Math.floor(Math.random() * 29)];
  const frase4 = f4[Math.floor(Math.random() * 29)];
  const frase5 = f5[Math.floor(Math.random() * 29)];
  const frase6 = f6[Math.floor(Math.random() * 29)];

  const far = document.querySelector('img');
  far.addEventListener('click', frases);

  function frases() {
    const frase = document.querySelector('.sub-titulo');
    frase.innerHTML = frase1 + frase2 + frase3 + frase4 + frase5 + frase6;
    const imagen = (document.querySelector('img').src = ` img/maqui${Math.floor(
      Math.random() * 9 + 2,
    )}.png`);

    if (imagen.length == 16) {
      document.querySelector('img').src = 'img/maqui10.gif';
      document.body.style.color = 'black';
    } else {
      document.body.style.backgroundColor = '';
      document.body.style.color = '';
    }
    console.log(imagen.length);
  }
}
