function total() {
  let f1 = [
    ' Dado',
    ' Baixo',
    ' Como',
    ' Bola',
    ' Hoje',
    ' Amanha',
    ' Procurar',
    ' Cativeiro',
    ' Você',
    ' Bombeiros',
    ' Crescente',
    ' Tesouro',
    ' Porque',
    ' Social  ',
    ' Matemática',
    ' Milho',
    ' Ontem',
    ' Trinta',
    ' Musica',
    ' Atoa',
    ' Pato',
    ' Vida',
    ' Morte',
    ' Pato',
    ' Gato',
    ' brilha',
    ' Fruta',
    ' Pena',
    ' Mesmo',
    ' Talvez',
    ' é',
    ' Coisa',
    ' eita',
    ' seria',
    ' quem',
    ' da',
    ' do',
    ' sim',
    ' vez',
    ' não',
    ' e',
    ' a',
    ' poxa',
    ' qual',
    ' que',
    ' isso',
    ' Pato',
    ' eu',
    ' tenha',
    ' faz',
    ' fez',
    ' para',
    ' por',
    ' vish',
    ' eita',
    ' tipo',
    ' dose',
    ' uma',
    ' mesmo',
    ' talvez',
    ' fugir',
    ' pneus',
    ' orquestra',
    ' cultura',
    ' bazuca',
    ' humano',
    ' quem',
    ' pacotes',
    ' carta',
    ' triplo',
    ' link',
    ' desligar',
    ' apertado',
    ' escolta',
    ' traseiro',
    ' tornado',
    ' laranja',
    ' cinquenta',
    ' laranja',
    ' cenoura',
    ' dividir',
    ' anedota',
    ' carro',
    ' ecologista',
    ' Pato',
    ' aventura',
    ' debate',
    ' agudo',
    ' equipamento',
    ' utilidade',
    ' é',
    ' ,',
    ' eita',
    ' seria',
    ' quem',
    ' da',
    ' do',
    ' sim',
    ' vez',
    ' não',
    ' e',
    ' a',
    ' poxa',
    ' qual',
    ' que',
    ' está',
    ' talvez',
    ' eu',
    ' tenha',
    ' faz',
    ' fez',
    ' para',
    ' por',
    ' vish',
    ' eita',
    ' outro',
    ' dose',
    ' uma',
    ' mesmo',
    ' Pato',
    ' girassol',
    ' consoantes',
    ' leite',
    ' montanha',
    ' triste',
    ' feliz',
    ' dez',
    ' derrama',
    ' praga',
    ' senta',
    ' girafa',
    ' 42',
    ' carteira',
    ' resumo',
    ' Pato',
    ' peso',
    ' manunteção',
    ' grupo',
    ' patamar',
    ' cerveja',
    ' mar',
    ' skate',
    ' borboleta',
    ' barraco',
    ' tijolo',
    ' coração',
    ' eclipse',
    ' sorrir',
    ' vera',
    ' virada',
    ' ?',
    ' igual',
    ' torneio',
    ' tomou',
    ' Pato',
    ' ocupado',
    ' visita',
    ' olho',
    ' lagoa',
    ' bengala',
    ' baixo',
    ' cubo',
    ' corre',
    ' cubo',
    ' ilha',
    '.',
    '!!',
    '...',
    ' quebra',
    ' ei!',
    ' banco',
    ' malote',
    ' briga',
    ' Matuê',
    ' irmão',
    ' rum',
    ' lancha',
    ' bem',
    ' mal',
    ' filme',
  ];
  let frase1 = f1[Math.floor(Math.random() * 180)];
  let frase2 = f1[Math.floor(Math.random() * 180)];
  let frase3 = f1[Math.floor(Math.random() * 180)];
  let frase4 = f1[Math.floor(Math.random() * 180)];
  let frase5 = f1[Math.floor(Math.random() * 180)];
  let frase6 = f1[Math.floor(Math.random() * 180)];

  frases();
  function frases() {
    let frase = document.querySelector('.sub-titulo');
    frase.innerHTML = frase1 + frase2 + frase3 + frase4 + frase5 + frase6;
    let imagen = (document.querySelector('img').src = ` img/maqui${Math.floor(
      Math.random() * 10 + 1,
    )}.png`);
    console.log(imagen);
    if (imagen.length == 16) {
      document.querySelector('img').src = 'img/maqui10.gif';
      document.body.style.color = 'black';
    } else {
      document.body.style.color = '';
    }
  }
  corBackground();
  function corBackground() {
    let r = Math.floor(Math.random() * 256);
    let g = Math.floor(Math.random() * 256);
    let b = Math.floor(Math.random() * 256);
    let color = 'rgb(' + r + ',' + g + ',' + b + ')';
    document.body.style.background = color;
  }
}
